name: Deploy Java app to Azure Web App

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: share-book
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
  JAVA_VERSION: '1.11'
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

jobs:
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
      - uses: actions/checkout@master
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build with Maven
        run: mvn package
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'